/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package online_monopoly;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JPanel;

/**
 *
 * @author n0krashy
 */
public class BoardPanel extends javax.swing.JPanel {

    BoardPanel _this;
    static ArrayList<Player> players = new ArrayList<Player>();
    BufferedImage image;

    boolean alreadyMoving = false;
    public int x = 550, y = 550;
    int distanceLeft;

    int step = 5;

    Dice dice = new Dice();

    /**
     * Creates new form BoardPanel
     */
    public BoardPanel() {
        initComponents();
        _this = this;

        RollDiceButton.setVisible(false);
        players.add(new Player("Hossam", Color.BLUE));
        players.add(new Player("Fady", Color.BLACK));
        players.add(new Player("Abdo", Color.RED));
        players.add(new Player("Hassan", Color.GREEN));
        try {
            image = ImageIO.read(new File("src/online_monopoly/misc/monopolyimg.jpg"));
            Dimension size = new Dimension(image.getWidth(), image.getHeight());
            setPreferredSize(size);
            setMinimumSize(size);
            setMaximumSize(size);
            setSize(size);
        } catch (IOException ex) {
            System.out.println("File not found");
        }
        
    }

    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g); //To change body of generated methods, choose Tools | Templates.
    g.drawImage(image, 0, 0, this.getWidth(), this.getHeight(), null);

//        for (int i = 0; i < players.size(); i++) {
//            g.setColor(players.get(i).getColor());
//            g.fillOval(players.get(i).getX(), players.get(i).getY(), 15, 15);
//        }
        g.setColor(Color.RED);
        g.fillOval(GameFrame.x, GameFrame.y, 15, 15);
        jLabel1.repaint();
        g.dispose();
    
    }

//    @Override
//    public void paint(Graphics g) {
//        super.paint(g);
//       g.drawImage(image, 0, 0, this.getWidth(), this.getHeight(), null);
//
////        for (int i = 0; i < players.size(); i++) {
////            g.setColor(players.get(i).getColor());
////            g.fillOval(players.get(i).getX(), players.get(i).getY(), 15, 15);
////        }
//        g.setColor(Color.RED);
//        g.fillOval(x, y, 15, 15);
//
//        g.dispose();
//    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        RollDiceButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        RollDiceButton.setText("Let's Roll !");
        RollDiceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RollDiceButtonActionPerformed(evt);
            }
        });
        add(RollDiceButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 230, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("0");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 200, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("0");
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 200, -1, -1));
    }// </editor-fold>                        

    private void RollDiceButtonActionPerformed(java.awt.event.ActionEvent evt) {                                               
        // TODO add your handling code here:

    }                                              


    // Variables declaration - do not modify                     
    private javax.swing.JButton RollDiceButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration                   
}
