/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package online_monopoly;

/**
 *
 * @author Kero
 */
public class PlayerTab extends javax.swing.JPanel {

    /**
     * Creates new form PlayerTab
     */
    public PlayerTab(String Name, int Money) {
        initComponents();
        this.PName.setText(Name);
        this.Pmoney.setText(Money+"");
    }
    
    public String TabName(){
        return this.PName.getText();
    }
    
    public void Setmoney(int money)
    {
        this.Pmoney.setText(money+"");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PName = new javax.swing.JLabel();
        Pmoney = new javax.swing.JLabel();

        setOpaque(false);
        setRequestFocusEnabled(false);
        setVerifyInputWhenFocusTarget(false);

        PName.setText("Name");

        Pmoney.setText("Money");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(PName)
                .addGap(62, 62, 62)
                .addComponent(Pmoney)
                .addContainerGap(225, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PName)
                    .addComponent(Pmoney))
                .addContainerGap(434, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel PName;
    private javax.swing.JLabel Pmoney;
    // End of variables declaration//GEN-END:variables
}
