/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package online_monopoly;

import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.ImageIcon;
/**
 *
 * @author fadia
 */
public class PlayerNameAndCharacterImagePickerFrame extends javax.swing.JFrame {

    /**
     * Creates new form PlayerNameAndCharacterImagePickerFrame
     */
    
    private ArrayList<ImageIcon> images = new ArrayList<>();
    private HashMap<String,String> playersImagesAssociation = new HashMap<>();
    private int playersLeft;
    private int selected;
    public PlayerNameAndCharacterImagePickerFrame(){
        
    }
    public PlayerNameAndCharacterImagePickerFrame(ArrayList<ImageIcon> images , HashMap<String,String> playersImagesAssociation, int playersLeft) {
        this.playersImagesAssociation = playersImagesAssociation;
        this.images = images;
        this.playersLeft = playersLeft; 
        initComponents();
        this.jLabel1.setIcon(this.images.get(this.getNewImage(true)));
        this.setVisible(true);
        this.setLocationRelativeTo(null);
    }

    private int getNewImage(boolean nextEqTruePreviouseqFalse){
        int increment = (nextEqTruePreviouseqFalse)? 1 : (PickingNumberOPlayersFrame.maxNumberOfSupportedPlayers-1);
        for(int i = (this.selected+increment)%4; i != this.selected; i = (i+increment)%4){
            if(playersImagesAssociation.get(""+i) == null) {
                return (this.selected = i);
            }
        }
        return this.selected;
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setOpaque(false);

        jButton1.setFont(new java.awt.Font("Vivaldi", 1, 36)); // NOI18N
        jButton1.setText("<");
        jButton1.setOpaque(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);

        jLabel1.setAlignmentX(0.5F);
        jPanel1.add(jLabel1);

        jButton2.setFont(new java.awt.Font("Vivaldi", 1, 36)); // NOI18N
        jButton2.setText(">");
        jButton2.setOpaque(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 420, 220));

        jLabel3.setFont(new java.awt.Font("Vivaldi", 1, 24)); // NOI18N
        jLabel3.setText("Player Name : ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 160, 40));

        jTextField1.setFont(new java.awt.Font("Vivaldi", 1, 18)); // NOI18N
        jTextField1.setOpaque(false);
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 220, 220, 40));

        jButton3.setFont(new java.awt.Font("Vivaldi", 1, 18)); // NOI18N
        jButton3.setText("Next");
        jButton3.setOpaque(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 300, 90, 40));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 51, 51));
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 400, 20));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/online_monopoly/mischd/background.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-3, 1, 440, 360));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.jLabel1.setIcon(images.get(this.getNewImage(false)));
//        System.out.println(this.selected);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        String name = jTextField1.getText();
        if(name!=null && !name.equals("")){
            for(String str : playersImagesAssociation.values()){
                if(str != null && name.equals(str)){
                    jLabel4.setText("Please enter a different name.");
                    return;
                }
            }
            playersImagesAssociation.put(this.selected+"", name);
            if(this.playersLeft == 0){
                new Mainboard_GUI_HD(0, 0, playersImagesAssociation);
            }
            else{
                new PlayerNameAndCharacterImagePickerFrame(images, playersImagesAssociation, playersLeft-1);
            }
            this.dispose();
        }else{
            jLabel4.setText("Please enter a valid name");
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.jLabel1.setIcon(images.get(this.getNewImage(true)));
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PlayerNameAndCharacterImagePickerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PlayerNameAndCharacterImagePickerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PlayerNameAndCharacterImagePickerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PlayerNameAndCharacterImagePickerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new PlayerNameAndCharacterImagePickerFrame(null,null,0).setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
